### ISSUE TITLE
read jsonl from stdin

### ISSUE THREAD

**Issue by chapmanjacobd** [domoritz/json2parquet#100] opened 2022-10-15 05:08 UTC
It would be nice if stdin was supported:

```
unzstd --memory=2048MB --stdout RS_2008-02.jsonl.zst | json2parquet out.parq
```

**Comment by domoritz** [comment] 2022-10-15 12:38
Duplicate of https://github.com/domoritz/csv2parquet/issues/40

**Closed** 2022-10-15 12:38 UTC
